version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: cbio-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: cbioportal
      MYSQL_USER: cbio
      MYSQL_PASSWORD: P@ssword1
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./seed-db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cbio-net

  cbioportal:
    build: .
    container_name: cbioportal-dev
    depends_on:
      - mysql
    volumes:
      - .:/cbioportal  # ✅ 改這行，包含 .git
    ports:
      - "8080:8080"
    working_dir: /cbioportal/backend/cbioportal
    stdin_open: true
    tty: true
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/cbioportal?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: cbio
      SPRING_DATASOURCE_PASSWORD: P@ssword1
      PORTAL_AUTHENTICATE: false
      JAVA_OPTS: -Dauthenticate=noauthsessionservice -Dremote.session.service.enabled=false
      GIT_DIR: /cbioportal/.git  # ✅ 加這行讓 Maven 插件能找到 .git
    networks:
      - cbio-net



  cbioportal-frontend:
    build: .
    container_name: cbioportal-frontend
    working_dir: /cbioportal/frontend
    command: bash -c "yarn install --frozen-lockfile && yarn run buildDLL:dev && yarn run buildModules && tail -f /dev/null"
    volumes:
      - .:/cbioportal  # ✅ 只保留這個
    ports:
      - "${PORT:-3000}:3000"
    environment:
      CBIOPORTAL_URL: ${CBIOPORTAL_URL}
      GENOME_NEXUS_URL: ${GENOME_NEXUS_URL}
      BRANCH_ENV: master
      HOST: 0.0.0.0
      PUBLIC_HOST: ${PUBLIC_HOST:-localhost}
      PORT: ${PORT:-3000}
      GIT_DISCOVERY_ACROSS_FILESYSTEM: "1"
    networks:
      - cbio-net


volumes:
  mysql_data:

networks:
  cbio-net:
    driver: bridge
